# Generated by Django 4.0.5 on 2022-10-05 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_alter_user_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
